// <auto-generated />
namespace tattlr.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class kk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kk));
        
        string IMigrationMetadata.Id
        {
            get { return "201406192348113_kk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
